name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev libcunit1-dev
      - name: Set up Python for gcovr
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install gcovr
        run: pip install gcovr
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Coverage
      - name: Build
        run: cmake --build build
      - name: Test
        working-directory: build
        run: ctest
      - name: Generate coverage report
        run: gcovr -r .. --branches --cobertura > coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
